FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npx prisma generate
RUN npm run build

FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
COPY --from=builder /app/dist ./dist

RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "start:docker"]
